name: Post JSON with Postman

on: workflow_dispatch

jobs:
  post-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman collection
      run: newman run config/collection_pmoyano.json --global-var "url=https://postman-echo.com/post" --global-var "payload=$(< config/pmoyano.json)"
